# Generated by Django 3.2.4 on 2021-08-23 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabLabUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('rfid_uuid', models.IntegerField()),
                ('can_brief', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SafetyBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(max_length=500)),
                ('validity_period', models.IntegerField()),
                ('document', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserIsBriefed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('instructor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='print.fablabuser')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='print.fablabuser')),
                ('safety_briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.safetybriefing')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('name', models.TextField()),
                ('host_name', models.TextField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.machinecategory')),
            ],
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='safety_briefings',
            field=models.ManyToManyField(through='print.UserIsBriefed', to='print.SafetyBriefing'),
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
