# Generated by Django 3.2.4 on 2021-08-23 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabLabUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=200)),
                ('rfid_uuid', models.IntegerField()),
                ('can_brief', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SafetyBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(max_length=500)),
                ('validity_period', models.IntegerField()),
                ('document', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='UserIsBriefed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('instructor_id', models.IntegerField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.fablabuser')),
                ('safety_briefings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.safetybriefing')),
            ],
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='safety_briefings',
            field=models.ManyToManyField(through='print.UserIsBriefed', to='print.SafetyBriefing'),
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
