# Generated by Django 3.2.4 on 2021-08-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userisbriefed',
            old_name='safety_briefings',
            new_name='safety_briefing',
        ),
        migrations.RemoveField(
            model_name='userisbriefed',
            name='instructor_id',
        ),
        migrations.AddField(
            model_name='userisbriefed',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='print.fablabuser'),
        ),
        migrations.AlterField(
            model_name='userisbriefed',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='print.fablabuser'),
        ),
    ]
