# Generated by Django 3.2.4 on 2021-07-15 13:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('print', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrintStack',
            new_name='Print',
        ),
        migrations.RenameField(
            model_name='printer',
            old_name='printStack',
            new_name='print',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='printStack',
            new_name='print',
        ),
    ]
