# Generated by Django 3.2.4 on 2021-08-23 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0002_auto_20210823_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='previous',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='print.model'),
        ),
    ]
