# Generated by Django 3.2.4 on 2021-08-24 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0003_alter_model_previous'),
    ]

    operations = [
        migrations.CreateModel(
            name='GcodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_location', models.FilePathField()),
                ('estimated_printing_time', models.TimeField()),
                ('used_filament_in_g', models.FloatField()),
                ('used_filament_in_mm', models.FloatField()),
                ('uploaded', models.DateTimeField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.model')),
            ],
        ),
    ]
