# Generated by Django 3.2.4 on 2021-08-24 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0004_gcodemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('state', models.IntegerField()),
                ('gcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='print.gcodemodel')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.machine')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='print.fablabuser')),
            ],
        ),
    ]
