# Generated by Django 3.2.4 on 2021-08-24 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0005_printjob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GcodeModel',
            new_name='GCode',
        ),
        migrations.RenameField(
            model_name='printjob',
            old_name='gcode',
            new_name='g_code',
        ),
        migrations.CreateModel(
            name='PrintTemperatureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_target', models.FloatField()),
                ('tool_actual', models.FloatField()),
                ('bed_target', models.FloatField()),
                ('bed_actual', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('print_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.printjob')),
            ],
        ),
    ]
