# Generated by Django 3.2.4 on 2021-08-24 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0006_auto_20210824_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcode',
            name='shared_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='print.fablabuser'),
        ),
        migrations.AddField(
            model_name='model',
            name='shared_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_by_user', to='print.fablabuser'),
        ),
        migrations.AlterField(
            model_name='model',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='print.fablabuser'),
        ),
        migrations.CreateModel(
            name='SlicingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_1', models.IntegerField()),
                ('parameter_n', models.IntegerField()),
                ('g_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.gcode')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('rating', models.IntegerField()),
                ('print_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.printjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.fablabuser')),
            ],
        ),
        migrations.CreateModel(
            name='PrintMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_location', models.FilePathField()),
                ('description', models.TextField()),
                ('print_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.printjob')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.fablabuser')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='user',
            field=models.ManyToManyField(through='print.AssignedUsers', to='print.FabLabUser'),
        ),
    ]
