# Generated by Django 3.2.4 on 2021-08-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0007_auto_20210824_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeDimensionalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FilePathField()),
                ('Uploaded', models.DateTimeField()),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='print.fablabuser')),
                ('Previous', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='print.threedimensionalmodel')),
                ('SharedWithUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_by_user', to='print.fablabuser')),
            ],
        ),
        migrations.AlterField(
            model_name='gcode',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.threedimensionalmodel'),
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
