# Generated by Django 3.2.4 on 2021-08-28 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import print.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('print', '0010_auto_20210828_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedusers',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gcode',
            name='SharedWithUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='User',
            field=models.ManyToManyField(through='print.AssignedUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='GCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='print.gcode'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='Machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='print.machine'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='User',
            field=models.ForeignKey(on_delete=models.SET(print.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='User',
            field=models.ForeignKey(on_delete=models.SET(print.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='threedimensionalmodel',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='threedimensionalmodel',
            name='SharedWithUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SharedWithUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userisbriefed',
            name='Instructor',
            field=models.ForeignKey(default=None, on_delete=models.SET(print.models.get_sentinel_user), related_name='Instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
