# Generated by Django 3.2.6 on 2021-09-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0011_auto_20210828_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinecategory',
            old_name='Name',
            new_name='NameTest',
        ),
    ]
