# Generated by Django 3.2.6 on 2021-09-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0012_rename_name_machinecategory_nametest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinecategory',
            old_name='NameTest',
            new_name='Name',
        ),
    ]
