# Generated by Django 3.2.4 on 2021-07-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printstack',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='printStack',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Printer',
        ),
        migrations.DeleteModel(
            name='PrintStack',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
